[theme]
primaryColor = "#011f54ff"       # Deep Blue (Buttons, Accents)
backgroundColor = "#D9D9D9"    # Concerto (Main Page Background)
secondaryBackgroundColor = "#B1BBC8" # Glacial Salt (Sidebar, Secondary Boxes)
textColor = "#111111"          # Near Black for high contrast text
font = "monospace"